# Generated by Django 5.0.6 on 2024-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_image', models.ImageField(upload_to='doctors/')),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
