# Generated by Django 5.0.6 on 2024-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_age', models.IntegerField()),
                ('p_gender', models.CharField(max_length=100)),
                ('p_contact', models.IntegerField()),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
    ]
